[build]
  command = "npm install"
  publish = "public"

[[redirects]]
  from = "/send"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/postuler"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
